name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Set up JDK
  #     uses: actions/setup-java@v2
  #     with:
  #       distribution: 'adopt'
  #       java-version: '20'
        
  #   - name: Make Gradlew Executable
  #     run: chmod +x ./gradlew

  #   - name: Build with Gradle
  #     run: ./gradlew build

  release:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '20'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v0.9
        release_name: Testing
        body: |
          Changes in this release:
          - Add your release notes here
        draft: false
        prerelease: false

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        
    
